const Constant = {
    TESTING : true,
    BASE_URL: 'http://itdev.mobifone.vn/iSchoolService/rest/mobilews/v2',
    // BASE_URL: 'http://10.4.200.37:7001/iSchoolService/rest/mobilews/v2',
    KEY: '0MYOo0bDLU3QgA7Om2YaoWPhr2UtFW9h',
    SCROLL_THRESHOLD : 150,
    API: {
        FETCH_NEWS : '/getNewsInCategory',
        GET_AUTH_TOKEN : '/getAuthToken',
        LOGIN : '/checkLogin',
        REGISTER : '/register',
        GET_SUB_AREA : '/getSubArea',
        GET_AREA_BY_NAME : '/getAreaByName',
        GET_HOMEPAGE : '/getHomePageData',
        GET_TAB_BADGES : '/getTabBadges',
        GET_RECORDS : '/getRecords',
        GET_NEWS : '/getNews',
        GET_SURVEYS : '/getSurveys',
        CHANGE_PASSWORD: '/changePassword',
        COMMENT_NEWS: '/commentNews',
        LIKE_NEWS: '/likeNews',
        GET_NEWS_INCLUDE_PARENT: '/getNewsIncludeParent',
        INIT_PAYMENT: '/initPayment',
        CHECK_BILL: '/checkBill',
        PAYMENT_HISTORY : '/paymentHistory',
        GET_RECORDS_EXCLUDE_PARENT: '/getRecordsExcludeParent',
        INSERT_TOKEN: '/insertToken',
        GET_SENSOR_LIST: '/getSensorList',
        GET_SENSOR_HISTORY: '/getSensorHistory',
        GET_ADS_LIST: '/getAdsList',
        GET_APP_CONFIGS: '/getAppConfigs',
        UPDATE_DOOR_WARNING_SCHEDULE: '/updateDoorWarningSchedule',
        VERIFY_REGISTER_OTP : '/verifyRegisterOtp',
        GET_PAY_TOKEN : '/getPayTokens',
        PAY_WITH_TOKEN : '/payWithToken',
        GET_LATES_NEWS : '/getLatestNews',
        GET_CAMERA_LIST : '/getCameraList',
        GET_NOTIFICATION_NEWS : '/getLatestNotifications',
        GET_EVENT_NEWS : '/getLatestEvents',
        GET_NEWS_DETAIL : '/getNormalNewsDetail',//get detail news
        GET_SCHEDULE_LIST : '/getScheduleList',
        GET_TEACHER_LIST_OF_CLASS : '/getTeachersListOfClass',
        GET_LIST_PARENT_OF_CLASS : '/getListParentsOfClass',
        UPDATE_USER_INFO : '/updateUserInfo',
        GET_OTP : '/getForgotPasswordOtp',
        VERIFY_OTP : '/verifyForgotPasswordOtp',
        GET_NORMAL_NEWS_FULL_DETAIL : '/getNormalNewsFullDetail',
        GET_RECORD_DETAIL : '/getRecordDetail',
        GET_NOTIFICATION_DETAIL : '/getNotificationDetail',
        GET_EVENT_DETAIL : '/getEventDetail',
        GET_MENU_LIST : '/getDailyMenu',
        GET_CHILD_MESSAGE : '/getChildMessage',
        GET_MESSAGE_DETAIL : '/getMessageDetail'
    },
    MESSAGES: {
        EXCEPTION: 'Kết nối mạng không ổn định. Vui lòng kiểm tra và thử lại sau.',
        NO_USERNAME_PASSWORD: 'Chưa nhập tên đăng nhập hoặc mật khẩu. Vui lòng kiểm tra lại!',
        TITLE_ALERT: 'Thông báo',
        TITLE_CONFIRM: 'Xác nhận',
        SUCCESS_REGISTER: 'Bạn đã đăng ký tài khoản thành công.',
        SUCCESS_CHANGE_PASS: 'Bạn đã thay đổi mật khẩu thành công.',
        BTN_OK: 'OK',
        BTN_CANCEL: 'Hủy bỏ',
        INVALID_AREA : 'Tài khoản đăng ký chưa đủ thông tin địa bàn',
        CONFIRM_LOGOUT_TITLE : 'Quý khách có chắc chắn muốn thoát khỏi ứng dụng?',
        CONFIRM_EXIT_TITLE : 'Bạn có chắn muốn thoát khỏi ứng dụng?',
        FAIL_LOAD_CONFIG: 'Không kiểm tra được cấu hình ứng dụng. Quý khách vui lòng thử lại sau',
        FORCE_UPDATE : 'Ứng dụng đã có phiên bản mới. Vui lòng cập nhật ứng dụng để tiếp tục sử dụng',
        OPTIONAL_UPDATE : 'Ứng dụng đã có phiên bản mới. Vui lòng cập nhật ứng dụng'

    },
    RESPONSE_CODE: {
        MSG_SUCCESS: 'SUCCESS',
        EXIST_USERNAME: 'EXIST_USERNAME',
        BAD_CONTENT: 'BAD_CONTENT',
        WRONG_OLD_PASSWORD: 'WRONG_OLD_PASSWORD',
        EXIST_TOKEN: 'EXIST_TOKEN',
        MAX_TRY : 'MAX_TRY',
        WRONG_OTP : 'WRONG_OTP'
    },
    FORMAT_DATE: {
        TIME_FORMAT: 'YYYY-MM-DD HH:mm:ss.SSS',
        TIME_SERVER: 'YYYY-MM-DD HH:mm:ss',
        TIME_CLIENT: 'DD/MM/YYYY',
        TIME_CLIENT_ARTICLE: 'DD/MM/YYYY HH:mm:ss'
    }
};

export default Constant;
